name: Install Tools
description: Installs required build tools
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        # Only run this on Linux runners
        if [ "${RUNNER_OS}" == "Linux" ]; then
          if [ "$ACT" == "true" ]; then
            sudo apt-get -y update
            sudo apt-get -y install \
              p7zip-full \
              rsync
          fi

          sudo apt-get -y update
          sudo apt-get -y install \
            desktop-file-utils \
            icnsutils \
            libfuse2 \
            tree \
            xmlstarlet
        elif [ "${RUNNER_OS}" == "macOS" ]; then
          brew install \
            create-dmg \
            p7zip \
            tree \
            zip
        fi

