name: Install Tools
description: Installs required build tools
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if [ "$ACT" == "true" ]; then
          sudo apt-get -y update
          sudo apt-get -y install \
            p7zip-full \
            rsync
        fi
        sudo apt-get -y install \
          desktop-file-utils \
          libfuse2 \
          tree
